openapi: 3.0.1
info:
  title: Deus
  description: A plugin that runs local scripts and manages memories.
  version: 'v1'
servers:
  - url: http://localhost:5004
paths:
  /run_script:
    post:
      operationId: run_script
      summary: Run a script
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runScriptRequest'
      responses:
        "200":
          description: Script run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runScriptResponse'
  /memories/create:
    post:
      operationId: create_memory
      summary: Create a memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMemoryRequest'
      responses:
        "201":
          description: Memory created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createMemoryResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "415":
          description: Unsupported media type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /memories/list:
    get:
      operationId: list_memories
      summary: List memories
      responses:
        "200":
          description: Memories list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listMemoriesResponse'
  /memories/search:
    post:
      operationId: get_memory
      summary: Search for a memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchMemoryRequest'
      responses:
        "200":
          description: Memory search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchMemoryResponse'
        "404":
          description: Memory not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "415":
          description: Unsupported media type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    runScriptRequest:
      type: object
      properties:
        language:
          type: string
          description: The script language
        code:
          type: string
          description: The script code which has line endings properly escaped for JSON
    runScriptResponse:
      type: object
      properties:
        exitCode:
          type: integer
          description: The script process exit code - zero is no error
        stdout:
          type: string
          description: The stdout from the script process - scripts output data this way  
        stderr:
          type: string
          description: The stderr from the script process - scripts reports errors this way
    createMemoryRequest:
      type: object
      properties:
        description:
          type: string
          description: A unique identifier for the memory
        text:
          type: string
          description: The text content of the memory
    createMemoryResponse:
      type: object
      properties:
        description:
          type: string
          description: A unique identifier for the created memory
    listMemoriesResponse:
      type: array
      items:
        type: string
      description: A list of memory descriptions
    searchMemoryRequest:
      type: object
      properties:
        description:
          type: string
          description: A unique identifier for the memory to be searched
    searchMemoryResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
          description: An array of search results
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message
